const DS_DON_VI = {
    "Chi nhánh số 1": [
        "Điểm Hỗ trợ dịch vụ công số Tây Hồ",
        "Điểm Hỗ trợ dịch vụ công số Xuân Đỉnh",
        "Điểm Hỗ trợ dịch vụ công số Phú Thượng",
        "Điểm Hỗ trợ dịch vụ công số Hoàng Đạo Thúy",  
    ],
      "Chi nhánh số 2": [
        "Điểm Hỗ trợ dịch vụ công số Nghĩa Đô",
        "Điểm Hỗ trợ dịch vụ công số Cầu Giấy",
        "Điểm Hỗ trợ dịch vụ công số Yên Hòa",
        "Điểm Hỗ trợ dịch vụ công số Thanh Xuân",  
        "Điểm Hỗ trợ dịch vụ công số Phương Liệt",  
        "Điểm Hỗ trợ dịch vụ công số Khương Đình",  
    ],
      "Chi nhánh số 3": [
        "Điểm Hỗ trợ dịch vụ công số Đống Đa",
        "Điểm Hỗ trợ dịch vụ công số Ba Đình",
        "Điểm Hỗ trợ dịch vụ công số Giảng Võ",
        "Điểm Hỗ trợ dịch vụ công số Hoàn Kiếm",  
        "Điểm Hỗ trợ dịch vụ công số Cửa Nam",  
        "Điểm Hỗ trợ dịch vụ công số Văn Miếu - Quốc Tử Giám",  
        "Điểm Hỗ trợ dịch vụ công số Ô Chợ Dừa",  
        "Điểm Hỗ trợ dịch vụ công số Kim Liên",  
        "Điểm Hỗ trợ dịch vụ công số Ngọc Hà",  
        "Điểm Hỗ trợ dịch vụ công số Láng",  
        "Điểm Hỗ trợ dịch vụ công số Hồng Hà",  
        "Điểm Hỗ trợ dịch vụ công số Hoàng Cầu",  
    ],
      "Chi nhánh số 4": [
        "Điểm Hỗ trợ dịch vụ công số Yên Sở",
        "Điểm Hỗ trợ dịch vụ công số Hoàng Liệt",
        "Điểm Hỗ trợ dịch vụ công số Vĩnh Hưng",
        "Điểm Hỗ trợ dịch vụ công số Lĩnh Nam",
        "Điểm Hỗ trợ dịch vụ công số Lĩnh Nam",
        "Điểm Hỗ trợ dịch vụ công số Định Công", 
        "Điểm Hỗ trợ dịch vụ công số Tương Mai",
        "Điểm Hỗ trợ dịch vụ công số Bùi Huy Bích",
        "Điểm Hỗ trợ dịch vụ công số Lê Đại Hành", 
        "Điểm Hỗ trợ dịch vụ công số Bạch Mai",
        "Điểm Hỗ trợ dịch vụ công số Hai Bà Trưng",
        "Điểm Hỗ trợ dịch vụ công số Vĩnh Tuy",
        "Điểm Hỗ trợ dịch vụ công số Hoàng Mai",   
    ],
      "Chi nhánh số 5": [
        "Điểm Hỗ trợ dịch vụ công số Tây Tựu",
        "Điểm Hỗ trợ dịch vụ công số Phú Diễn", 
        "Điểm Hỗ trợ dịch vụ công số Đông Ngạc", 
        "Điểm Hỗ trợ dịch vụ công số Thượng Cát", 
        "Điểm Hỗ trợ dịch vụ công số Từ Liêm", 
        "Điểm Hỗ trợ dịch vụ công số Đại Mỗ", 
        "Điểm Hỗ trợ dịch vụ công số Tây Mỗ", 
        "Điểm Hỗ trợ dịch vụ công số Xuân Phương",
        "Điểm Hỗ trợ dịch vụ công số Hoài Đức", 
        "Điểm Hỗ trợ dịch vụ công số An Khánh", 
        "Điểm Hỗ trợ dịch vụ công số Dương Hòa", 
        "Điểm Hỗ trợ dịch vụ công số Sơn Đồng",  

    ],
      "Chi nhánh số 6": [
        "Điểm Hỗ trợ dịch vụ công số Việt Hưng",
        "Điểm Hỗ trợ dịch vụ công số Long Biên", 
        "Điểm Hỗ trợ dịch vụ công số Phúc Lợi",  
        "Điểm Hỗ trợ dịch vụ công số Bồ Đề", 
        "Điểm Hỗ trợ dịch vụ công số Gia Lâm", 
        "Điểm Hỗ trợ dịch vụ công số Phù Đổng 1", 
        "Điểm Hỗ trợ dịch vụ công số Phù Đổng 2", 
        "Điểm Hỗ trợ dịch vụ công số Thuận An", 
        "Điểm Hỗ trợ dịch vụ công số Bát Tràng", 

    ],
      "Chi nhánh số 7": [
        "Điểm Hỗ trợ dịch vụ công số Hà Đông",
        "Điểm Hỗ trợ dịch vụ công số Kiến Hưng", 
        "Điểm Hỗ trợ dịch vụ công số Dương Nội", 
        "Điểm Hỗ trợ dịch vụ công số Phú Lương", 
        "Điểm Hỗ trợ dịch vụ công số Yên Nghĩa", 
        "Điểm Hỗ trợ dịch vụ công số Quốc Oai", 
        "Điểm Hỗ trợ dịch vụ công số Kiều Phú", 
        "Điểm Hỗ trợ dịch vụ công số Phú Cát",
        "Điểm Hỗ trợ dịch vụ công số Hưng Đạo", 
        "Điểm Hỗ trợ dịch vụ công số Chương Mỹ", 
        "Điểm Hỗ trợ dịch vụ công số Hòa Phú", 
        "Điểm Hỗ trợ dịch vụ công số Phú Nghĩa", 
        "Điểm Hỗ trợ dịch vụ công số Quảng Bị",
        "Điểm Hỗ trợ dịch vụ công số Trần Phú",
        "Điểm Hỗ trợ dịch vụ công số Xuân Mai",  
    ],
      "Chi nhánh số 8": [
        "Điểm Hỗ trợ dịch vụ công số Quang Minh", 
        "Điểm Hỗ trợ dịch vụ công số Mê Linh", 
        "Điểm Hỗ trợ dịch vụ công số Yên Lãng", 
        "Điểm Hỗ trợ dịch vụ công số Tiến Thắng", 
        "Điểm Hỗ trợ dịch vụ công số Đông Anh", 
        "Điểm Hỗ trợ dịch vụ công số Phúc Thịnh",
        "Điểm Hỗ trợ dịch vụ công số Thiên Lộc", 
        "Điểm Hỗ trợ dịch vụ công số Thư Lâm", 
        "Điểm Hỗ trợ dịch vụ công số Vĩnh Thanh",
        "Điểm Hỗ trợ dịch vụ công số Sóc Sơn", 
        "Điểm Hỗ trợ dịch vụ công số Đa Phúc", 
        "Điểm Hỗ trợ dịch vụ công số Kim Anh", 
        "Điểm Hỗ trợ dịch vụ công số Nội Bài",
        "Điểm Hỗ trợ dịch vụ công số Trung Giã",    
    ],
      "Chi nhánh số 9": [
        "Điểm Hỗ trợ dịch vụ công số Đan Phượng", 
        "Điểm Hỗ trợ dịch vụ công số Liên Minh",
        "Điểm Hỗ trợ dịch vụ công số Ô Diên", 
        "Điểm Hỗ trợ dịch vụ công số Phúc Thọ", 
        "Điểm Hỗ trợ dịch vụ công số Phúc Lộc", 
        "Điểm Hỗ trợ dịch vụ công số Hát Môn", 
        "Điểm Hỗ trợ dịch vụ công số Thạch Thất", 
        "Điểm Hỗ trợ dịch vụ công số Hạ Bằng", 
        "Điểm Hỗ trợ dịch vụ công số Hòa Lạc", 
        "Điểm Hỗ trợ dịch vụ công số Tây Phương", 
        "Điểm Hỗ trợ dịch vụ công số Yên Xuân", 
 
    ],
      "Chi nhánh số 10": [
        "Điểm Hỗ trợ dịch vụ công số Thanh Oai",
        "Điểm Hỗ trợ dịch vụ công số Bình Minh", 
        "Điểm Hỗ trợ dịch vụ công số Tam Hưng", 
        "Điểm Hỗ trợ dịch vụ công số Dân Hòa", 
        "Điểm Hỗ trợ dịch vụ công số Vân Đình", 
        "Điểm Hỗ trợ dịch vụ công số Hòa Xá", 
        "Điểm Hỗ trợ dịch vụ công số Ứng Thiên", 
        "Điểm Hỗ trợ dịch vụ công số Ứng Hòa", 
        "Điểm Hỗ trợ dịch vụ công số Mỹ Đức", 
        "Điểm Hỗ trợ dịch vụ công số Hồng Sơn",
        "Điểm Hỗ trợ dịch vụ công số Hương Sơn",
        "Điểm Hỗ trợ dịch vụ công số Phúc Sơn",  

    ],
      "Chi nhánh số 11": [
        "Điểm Hỗ trợ dịch vụ công số Phú Xuyên", 
        "Điểm Hỗ trợ dịch vụ công số Chuyên Mỹ", 
        "Điểm Hỗ trợ dịch vụ công số Đại Xuyên", 
        "Điểm Hỗ trợ dịch vụ công số Phượng Dực", 
        "Điểm Hỗ trợ dịch vụ công số Thanh Trì", 
        "Điểm Hỗ trợ dịch vụ công số Ngọc Hồi", 
        "Điểm Hỗ trợ dịch vụ công số Nam Phù", 
        "Điểm Hỗ trợ dịch vụ công số Thanh Liệt", 
        "Điểm Hỗ trợ dịch vụ công số Đại Thanh", 
        "Điểm Hỗ trợ dịch vụ công số Thường Tín", 
        "Điểm Hỗ trợ dịch vụ công số Chương Dương", 
        "Điểm Hỗ trợ dịch vụ công số Thượng Phúc", 
        "Điểm Hỗ trợ dịch vụ công số Hồng Vân", 
    ],
      "Chi nhánh số 12": [
        "Điểm Hỗ trợ dịch vụ công số Quảng Oai", 
        "Điểm Hỗ trợ dịch vụ công số Ba Vì", 
        "Điểm Hỗ trợ dịch vụ công số Vật Lại", 
        "Điểm Hỗ trợ dịch vụ công số Cổ Đô", 
        "Điểm Hỗ trợ dịch vụ công số Bất Bạt", 
        "Điểm Hỗ trợ dịch vụ công số Yên Bài", 
        "Điểm Hỗ trợ dịch vụ công số Minh Châu", 
        "Điểm Hỗ trợ dịch vụ công số Suối Hai", 
        "Điểm Hỗ trợ dịch vụ công số Sơn Tây",
        "Điểm Hỗ trợ dịch vụ công số Đoài Phương", 
        "Điểm Hỗ trợ dịch vụ công số Tùng Thiện", 

    ],
};
